//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPersonService")]
    public interface IPersonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/iAdd", ReplyAction="http://tempuri.org/IPersonService/iAddResponse")]
        int iAdd(int val1, int val2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/iAdd", ReplyAction="http://tempuri.org/IPersonService/iAddResponse")]
        System.Threading.Tasks.Task<int> iAddAsync(int val1, int val2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/iSub", ReplyAction="http://tempuri.org/IPersonService/iSubResponse")]
        int iSub(int val1, int val2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/iSub", ReplyAction="http://tempuri.org/IPersonService/iSubResponse")]
        System.Threading.Tasks.Task<int> iSubAsync(int val1, int val2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/iMul", ReplyAction="http://tempuri.org/IPersonService/iMulResponse")]
        int iMul(int val1, int val2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/iMul", ReplyAction="http://tempuri.org/IPersonService/iMulResponse")]
        System.Threading.Tasks.Task<int> iMulAsync(int val1, int val2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/iDiv", ReplyAction="http://tempuri.org/IPersonService/iDivResponse")]
        int iDiv(int val1, int val2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/iDiv", ReplyAction="http://tempuri.org/IPersonService/iDivResponse")]
        System.Threading.Tasks.Task<int> iDivAsync(int val1, int val2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/iMod", ReplyAction="http://tempuri.org/IPersonService/iModResponse")]
        int iMod(int val1, int val2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/iMod", ReplyAction="http://tempuri.org/IPersonService/iModResponse")]
        System.Threading.Tasks.Task<int> iModAsync(int val1, int val2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/CountAndMaxPrime", ReplyAction="http://tempuri.org/IPersonService/CountAndMaxPrimeResponse")]
        System.ValueTuple<int, int> CountAndMaxPrime(int l1, int l2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/CountAndMaxPrime", ReplyAction="http://tempuri.org/IPersonService/CountAndMaxPrimeResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<int, int>> CountAndMaxPrimeAsync(int l1, int l2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonServiceChannel : WcfClient.ServiceReference1.IPersonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonServiceClient : System.ServiceModel.ClientBase<WcfClient.ServiceReference1.IPersonService>, WcfClient.ServiceReference1.IPersonService {
        
        public PersonServiceClient() {
        }
        
        public PersonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int iAdd(int val1, int val2) {
            return base.Channel.iAdd(val1, val2);
        }
        
        public System.Threading.Tasks.Task<int> iAddAsync(int val1, int val2) {
            return base.Channel.iAddAsync(val1, val2);
        }
        
        public int iSub(int val1, int val2) {
            return base.Channel.iSub(val1, val2);
        }
        
        public System.Threading.Tasks.Task<int> iSubAsync(int val1, int val2) {
            return base.Channel.iSubAsync(val1, val2);
        }
        
        public int iMul(int val1, int val2) {
            return base.Channel.iMul(val1, val2);
        }
        
        public System.Threading.Tasks.Task<int> iMulAsync(int val1, int val2) {
            return base.Channel.iMulAsync(val1, val2);
        }
        
        public int iDiv(int val1, int val2) {
            return base.Channel.iDiv(val1, val2);
        }
        
        public System.Threading.Tasks.Task<int> iDivAsync(int val1, int val2) {
            return base.Channel.iDivAsync(val1, val2);
        }
        
        public int iMod(int val1, int val2) {
            return base.Channel.iMod(val1, val2);
        }
        
        public System.Threading.Tasks.Task<int> iModAsync(int val1, int val2) {
            return base.Channel.iModAsync(val1, val2);
        }
        
        public System.ValueTuple<int, int> CountAndMaxPrime(int l1, int l2) {
            return base.Channel.CountAndMaxPrime(l1, l2);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<int, int>> CountAndMaxPrimeAsync(int l1, int l2) {
            return base.Channel.CountAndMaxPrimeAsync(l1, l2);
        }
    }
}
